DATA:
  DIM: 2                  # data dimension
  BATCH_SIZE: 8 #16
  TEST_BATCH_SIZE: 16 #16
  DATA_PATH: '/nas/tsgil/dataset/Inria_building/train/' # Path to dataset, could be overwritten by command line argument
  TEST_DATA_PATH: '/nas/tsgil/dataset/Inria_building/test/' # 두 폴더 파일 똑같은 것 같음
  DATASET: 'Inria'     # Dataset name
  IMG_SIZE: [300, 300]    # Input image size
  NUM_WORKERS: 4          # Number of data loading threads
  SEED: 10                # random seed for reproducibility

TRAIN:
  EPOCHS: &epoch 80
  LR: 1e-4
  # LR_BACKBONE: 1e-4
  WEIGHT_DECAY: 1e-5
  LR_DROP: *epoch
  # CLIP_MAX_NORM: 0.1  # hardcoded

  SAVE_PATH: "./work_dirs/R2U_Net_pretrain/"          # save path for the checkpoint, log and val results
  VAL_INTERVAL: 10                  # validation interval
  SAVE_VAL: False                   # save validation data

log:
  exp_name: 'baseline_R2U_Net_pretrain_epoch80'
  message: "Baseline TopDig-Node-Detector for road network"
