DATA:
  DIM: 2                  # data dimension
  BATCH_SIZE: 8 #16
  TEST_BATCH_SIZE: 16 #16
  DATA_PATH: '/nas/tsgil/dataset/Inria_building/train/' # Path to dataset, could be overwritten by command line argument
  TEST_DATA_PATH: '/nas/tsgil/dataset/Inria_building/test/' # 두 폴더 파일 똑같은 것 같음
  DATASET: 'Inria'     # Dataset name
  IMG_SIZE: [300, 300]    # Input image size
  NUM_WORKERS: 4          # Number of data loading threads
  SEED: 10                # random seed for reproducibility

TRAIN:
  EPOCHS: &epoch 8
  LR: 2e-4 # Loss 
  LR_BACKBONE: 2e-4 # L_node
  WEIGHT_DECAY: 2e-5
  LR_DROP: *epoch

  SAVE_PATH: "./work_dirs/TopDiG_train/"          # save path for the checkpoint, log and val results
  VAL_INTERVAL: 4                  # validation interval
  SAVE_VAL: False                   # save validation data

  # loss weight
  LOSSES: ['node', 'graph']
  W_NODE: 10.0 # 조정 가능, loss_fn 안에서는 따로 또 가중치 있음.
  W_GRAPH: 1.0 # 폴리월드 논문과 동일하게 1


log:
  exp_name: 'baseline_TopDiG_train_epoch8'
  message: "Baseline TopDig for Inria dataset"
