DATA:
  BATCH_SIZE: 16
  DATA_PATH: '/nas/tsgil/dataset/Inria_building/train/' # Path to dataset, could be overwritten by command line argument
  TEST_DATA_PATH: '/nas/tsgil/dataset/Inria_building/test/' # 두 폴더 파일 똑같은 것 같음
  BACKBONE_PATH: '/nas/tsgil/gil/picked_backbone/epochs_130_5e-6.pth'
  BACKBONE_CONFIG_PATH: '/nas/tsgil/relationformer/configs/inria_pretrain.yaml'
  DATASET: 'Inria'     # Dataset name
  IMG_SIZE: [300, 300]    # Input image size resized [320, 320]
  NUM_WORKERS: 16          # Number of data loading threads
  SEED: 10                # random seed for reproducibility

MODEL:
  MATCHER: # 헝가리안 매쳐한테 가중치를 줘야 할지?
    C_NODE: 5
    C_CLASS: 3

TRAIN:
  EPOCHS: &epoch 20
  LR: 1e-4 # L_graph
  LR_BACKBONE: 1e-6 # L_node
  WEIGHT_DECAY: 1e-5
  LR_DROP: *epoch

  SAVE_PATH: "./work_dirs/TopDiG_train/"  # save path for the checkpoint, log and val results
  VAL_INTERVAL: *epoch                    # validation interval
  SAVE_VAL: False                         # save validation data

  # loss weight
  # the loss functions specific weights referred by relationformer
  LOSSES: ['node', 'graph1', 'graph2']
  W_NODE: 10.0 # 조정 가능, loss_fn 안에서는 따로 또 가중치 있음.
  W_GRAPH: 1.0 # 폴리월드 논문과 동일하게 1


log:
  exp_name: 'baseline_TopDiG_train_epoch20_poly'
  message: "Baseline TopDig for Inria dataset"
